env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  emcaVersion: 2021
plugins:
  - 'svelte3'
  - '@typescript-eslint'
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
settings:
  svelte3/typescript: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
overrides:
  - processor: svelte3/svelte3
    files:
      - '*.svelte'
